### ISSUE TITLE
UBports installer for windows hangs at "please reboot into bootloader"

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#116]
_From @arronlacey on March 3, 2018 22:25_

version: ubports-installer.0.1.11-beta

Oneplus One A00001 can be detected both by adb and fastboot, however when rebooting into bootloader as directed by UBports installer, the installer does not detect the device, it just hangs waiting for it. I can see the authorised device using fastboot:

$ ./fastboot.exe devices
a3672b68        fastboot

Other info:

- USB debugging/dev options/MTP are all enabled.
- TMwin recovery in installed
- I have wiped the device (including internal storage)

any other suggestions?

_Copied from original issue: ubports/ubuntu-touch#495_

**Comment by DrMagicWolf** [comment]
I can confirm this exact behavior, my device is detected by adb/fastboot and can be rebooted etc. but UBposts installer 0.1.12-beta does not recognize the device and stays at "Waiting for device..." and even after manually selecting the device and the options, it gets stuck at the "Please reboot to bootloader" screen.

**Comment by astearon** [comment]
I can confirm this as well

**Comment by Tofbee** [comment]
I confirm this on my bq aquaris e5 ubuntu edition

**Comment by NeoTheThird** [comment]
@Tofbee is your device running Android at the moment? Then it might be #221.

Thanks @DrMagicWolf and @astearon. What device is it in your case? Could you try installing the ADB driver specific to your device and try again? If that then works, we'll have to patch the Universal ADB driver. Thanks in advance!

**Comment by Tofbee** [comment]
Thank you for reply. No my device is an aquaris e5 from BQ with native ubuntu edition, not android. Can you tell me where i can find such specific adb driver ?

Thank you for your kind help

**Comment by DrMagicWolf** [comment]
My device is a OnePlus One ad I'm using the original ADB drivers.

**Comment by NeoTheThird** [comment]
Please try again with [the latest version](https://github.com/ubports/ubports-installer/releases/latest).

**Comment by whylwhyl** [comment]
Hi! I have the same problem. 
BQ Aquaris M10 Ubuntu edition
Windows 10 x64

**Comment by tomdertech** [comment]
Hi, 
I have the same problem Android on the M10 FHD and running the installer on Win 10 pro x64.
I have launched Android Studio and can successfully load an Andoid app on the M10 FHD from the Win 10 machine, so I know ADB drivers should be OK.

**Comment by fabrei** [comment]
i had the same problem. maybe [this](https://github.com/ubports/ubports-installer/issues/416#issuecomment-417250720) helps :)

**Comment by Tofbee** [comment]
> 
> 
> @Tofbee Ok, but you're on Windows as well? If so, here you go: http://www.androidusbdrivers.com/bq-aquaris-e5-fhd-usb-drivers/
> 
> If not, your problem is unrelated and I'll ask you to file a separate issue. You do not need to install a new driver on Linux or macOS.

Hi NeoTheThird,

I've tried under windows7 and 10, I've downloaded the driver and the new installer, but I notice no progress. I'm still stuck with the old ubuntu touch. I've you any idea of what to try now ?

Thank you for your help.

**Comment by NeoTheThird** [comment]
This should be fixed in the next release, if anyone wants to test: https://github.com/ubports/ubports-installer/releases/tag/0.2.0-beta

**Comment by retro486** [comment]
Nexus 5 in bootloader mode still not detected in 0.2.0 beta attempting manual installation. I'm using the suggested driver from the installer (identified as "Google Nexus BootLoader Interface" and works when I run fastboot commands). This new version also triggers the Windows 10 "You need  to install an app for this task" message for some reason...

**Comment by NeoTheThird** [comment]
Here's a newer version: https://github.com/ubports/ubports-installer/releases/tag/0.2.2-beta
